/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author JULI4
 */
public class Elemento3 extends javax.swing.JPanel {

    /**
     * Creates new form Elemento3
     */
    public Elemento3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Elemento3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_MagnitudCosF1 = new javax.swing.JTextField();
        txt_AnguloCosF1 = new javax.swing.JTextField();
        txt_MagnitudSenF1 = new javax.swing.JTextField();
        txt_MagnitudCosF3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_AnguloCosF2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_MagnitudSenF2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_AnguloSenF2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_AnguloSenF1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_MagnitudCosF2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_AnguloCosF3 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txt_MagnitudSenF3 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txt_AnguloSenF3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();

        Panel_Elemento3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("F1 =");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("F2 =");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("COS");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("+");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("°");

        txt_MagnitudCosF1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MagnitudCosF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_MagnitudCosF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MagnitudCosF1ActionPerformed(evt);
            }
        });
        txt_MagnitudCosF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MagnitudCosF1KeyReleased(evt);
            }
        });

        txt_AnguloCosF1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_AnguloCosF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_AnguloCosF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_AnguloCosF1KeyReleased(evt);
            }
        });

        txt_MagnitudSenF1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MagnitudSenF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_MagnitudCosF3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MagnitudCosF3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_MagnitudCosF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MagnitudCosF3ActionPerformed(evt);
            }
        });
        txt_MagnitudCosF3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MagnitudCosF3KeyReleased(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("COS");

        txt_AnguloCosF2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_AnguloCosF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_AnguloCosF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_AnguloCosF2KeyReleased(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("°");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("+");

        txt_MagnitudSenF2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MagnitudSenF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("SEN");

        txt_AnguloSenF2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_AnguloSenF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("°");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("°");

        txt_AnguloSenF1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_AnguloSenF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_AnguloSenF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AnguloSenF1ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("SEN");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("F3 =");

        txt_MagnitudCosF2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MagnitudCosF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_MagnitudCosF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MagnitudCosF2ActionPerformed(evt);
            }
        });
        txt_MagnitudCosF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MagnitudCosF2KeyReleased(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("COS");

        txt_AnguloCosF3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_AnguloCosF3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_AnguloCosF3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_AnguloCosF3KeyReleased(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("°");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("+");

        txt_MagnitudSenF3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MagnitudSenF3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("SEN");

        txt_AnguloSenF3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_AnguloSenF3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("°");

        javax.swing.GroupLayout Panel_Elemento3Layout = new javax.swing.GroupLayout(Panel_Elemento3);
        Panel_Elemento3.setLayout(Panel_Elemento3Layout);
        Panel_Elemento3Layout.setHorizontalGroup(
            Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                        .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                                .addComponent(txt_MagnitudCosF3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                                .addComponent(txt_MagnitudCosF2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                                .addComponent(txt_AnguloCosF3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_MagnitudSenF3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                                .addComponent(txt_AnguloCosF2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_MagnitudSenF2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                                .addComponent(txt_AnguloSenF2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                                .addComponent(txt_AnguloSenF3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                        .addComponent(txt_MagnitudCosF1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_AnguloCosF1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_MagnitudSenF1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AnguloSenF1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Panel_Elemento3Layout.setVerticalGroup(
            Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Elemento3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MagnitudCosF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txt_AnguloCosF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel32)
                    .addComponent(txt_MagnitudSenF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(txt_AnguloSenF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(21, 21, 21)
                .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_MagnitudCosF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txt_AnguloCosF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel28)
                    .addComponent(txt_MagnitudSenF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txt_AnguloSenF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(Panel_Elemento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txt_MagnitudCosF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(txt_AnguloCosF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel46)
                    .addComponent(txt_MagnitudSenF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(txt_AnguloSenF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Elemento3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Elemento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MagnitudCosF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MagnitudCosF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MagnitudCosF1ActionPerformed

    private void txt_MagnitudCosF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MagnitudCosF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MagnitudCosF3ActionPerformed

    private void txt_MagnitudCosF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MagnitudCosF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MagnitudCosF2ActionPerformed

    private void txt_AnguloSenF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AnguloSenF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AnguloSenF1ActionPerformed

    private void txt_MagnitudCosF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MagnitudCosF1KeyReleased
        // TBOTON DEL EVENTO F1 COS MAGNITUD
        String magnitudCos = txt_MagnitudCosF1.getText();
        txt_MagnitudSenF1.setText(magnitudCos);
        
    }//GEN-LAST:event_txt_MagnitudCosF1KeyReleased

    private void txt_MagnitudCosF2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MagnitudCosF2KeyReleased
         // BOTON DEL EVENTO F2 COS MAGNITUD
        String magnitudCos = txt_MagnitudCosF2.getText();
        txt_MagnitudSenF2.setText(magnitudCos);
        
        
        
    }//GEN-LAST:event_txt_MagnitudCosF2KeyReleased

    private void txt_MagnitudCosF3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MagnitudCosF3KeyReleased
         // BOTON DEL EVENTO F3 COS MAGNITUD
        String magnitudCos = txt_MagnitudCosF3.getText();
        txt_MagnitudSenF3.setText(magnitudCos);
        
        
    }//GEN-LAST:event_txt_MagnitudCosF3KeyReleased

    private void txt_AnguloCosF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AnguloCosF1KeyReleased
         // BOTON DEL EVENTO F1 COS MAGNITUD
        String anguloCos = txt_AnguloCosF1.getText();
        txt_AnguloSenF1.setText(anguloCos);
        
        
    }//GEN-LAST:event_txt_AnguloCosF1KeyReleased

    private void txt_AnguloCosF2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AnguloCosF2KeyReleased
        // BOTON DEL EVENTO F2 COS MAGNITUD
        String anguloCos = txt_AnguloCosF2.getText();
        txt_AnguloSenF2.setText(anguloCos);
    }//GEN-LAST:event_txt_AnguloCosF2KeyReleased

    private void txt_AnguloCosF3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AnguloCosF3KeyReleased
         // BOTON DEL EVENTO F3 COS MAGNITUD
        String anguloCos = txt_AnguloCosF3.getText();
        txt_AnguloSenF3.setText(anguloCos);
    }//GEN-LAST:event_txt_AnguloCosF3KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Elemento3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JTextField txt_AnguloCosF1;
    private javax.swing.JTextField txt_AnguloCosF2;
    private javax.swing.JTextField txt_AnguloCosF3;
    private javax.swing.JTextField txt_AnguloSenF1;
    private javax.swing.JTextField txt_AnguloSenF2;
    private javax.swing.JTextField txt_AnguloSenF3;
    private javax.swing.JTextField txt_MagnitudCosF1;
    private javax.swing.JTextField txt_MagnitudCosF2;
    private javax.swing.JTextField txt_MagnitudCosF3;
    private javax.swing.JTextField txt_MagnitudSenF1;
    private javax.swing.JTextField txt_MagnitudSenF2;
    private javax.swing.JTextField txt_MagnitudSenF3;
    // End of variables declaration//GEN-END:variables
}
